### ISSUE TITLE
Add Ligue 1 - France

### ISSUE THREAD

**Issue by ghost** [richecr/PySoccer#7]
**Add Ligue 1 leaderboard information**

- Leaderboard URL: https://www.transfermarkt.com.br/ligue-1/tabelle/wettbewerb/FR1/saison_id/2020

- League URL: https://www.transfermarkt.com.br/ligue-1/startseite/wettbewerb/FR1

**Comment by CaiqueCoelho** [comment]
i'll take this one :1st_place_medal:

**Comment by ghost** [comment]
If you have any questions, feel free to ask.

**Comment by ghost** [comment]
Hello @CaiqueCoelho, are you having any problems/doubts with this issue?

**Comment by ghost** [comment]
Due to the lack of answers from @CaiqueCoelho, I decided to open the issue to new developers.

**Comment by lucascz37** [comment]
Can i contribute to this issue?

**Comment by ghost** [comment]
Hi, yes you can. I'll put you in charge of this issue.
