### ISSUE TITLE
Add bundesliga - Germany

### ISSUE THREAD

**Issue by ghost** [richecr/PySoccer#8]
**Add bundesliga leaderboard information**

- Leaderboard URL: https://www.transfermarkt.com.br/1-bundesliga/tabelle/wettbewerb/L1/saison_id/2020

- Leaguue URL: https://www.transfermarkt.com.br/1-bundesliga/startseite/wettbewerb/L1

**Comment by lucascz37** [comment]
i'll take this one :+1:
